### ISSUE TITLE
Metrics with next reservation timestamp

### ISSUE THREAD

**Issue by mpromain** [FUSAKLA/exchange-meeting-room-exporter#1]
Export metrics with next reserved block for each meeting room.

I prefer timestamp value for easy compute free minutes.

**Comment by FUSAKLA** [comment]
Hi, yes that would be definitely useful!

Another useful information could be for already reserved rooms a timestamp when it gets available again. 

The question is how long to the future to look for those reservations and what will be the value in case that there is no reservation (something representing null)
